// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Deleted struct {
	PostID int64
}

type Meta struct {
	PostID    int64
	Slug      string
	Title     string
	Summary   string
	GroupName sql.NullString
	Tags      []string
	PostTime  time.Time
}

type Post struct {
	ID      int64
	Content string
}
